### ISSUE TITLE
 Class FoxxMD\LaravelElasticBeanstalkQueueWorker\ElasticBeanstalkQueueWorkerProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register)

### ISSUE THREAD

**Issue by PLaRoche** [FoxxMD/laravel-elasticbeanstalk-queue-worker#5]
When `php artisan vendor:publish --tag=ebworker`

**Comment by FoxxMD** [comment]
Woops! Truth be told I haven't eaten my own dogfood yet :) I've got some free time tomorrow/friday that I plan on using to get this implemented in the projects I originally extracted it from. I'll get this sorted out!

**Comment by PLaRoche** [comment]
great, will keep following, you have inspired me to move my docker stuff into a similar package so I stop copying and pasting docker-compose, dockerfile, etc to all my laravel apps

**Comment by FoxxMD** [comment]
Let me know if you have any more problems!
