### ISSUE TITLE
Questions about 'Add Queues'

### ISSUE THREAD

**Issue by slumrig** [FoxxMD/laravel-elasticbeanstalk-queue-worker#8]
2 questions:

1) If I don't have a named queue what do I put in the placeholders - queue[QueueName]=[queueName]? 

I just want it to run all pending jobs like queue:listen so I don't have specifically named queues.

2) is the naming convention for queue[QueueName] like 'queue' - no space - 'the queue name'?

Thanks!

**Comment by FoxxMD** [comment]
> If I don't have a named queue what do I put in the placeholders - queue[QueueName]=[queueName]?

I mentioned in the [caveats](https://github.com/FoxxMD/laravel-elasticbeanstalk-queue-worker#caveats) that I built this for use with beanstalkd which only has named queues, so I didn't write a way to generate a configuration without a queue name. 

However it would be easy to modify! All you need to do is rework `parseConfig.php` so:

* `$queue` param in `generateProgram()` is optional
* the `foreach` checking the environmental variables either doesn't pass a variables for `$queue` if the value is some magic string (or something)

> is the naming convention for queue[QueueName] like 'queue' - no space - 'the queue name'?

Yes. In the environmental variables the key is case insensitive but the value is not. Here's a screenshot from one of my environments

![screen shot 2018-02-01 at 10 25 33 am](https://user-images.githubusercontent.com/4663766/35686497-627ed834-073a-11e8-8e45-2aaf0f7ee6a4.png)

`exportOrders` is the name of the queue on beanstalkd.

**Comment by slumrig** [comment]
Thanks! I will take a closer look. My bad for not reading the caveats - sometimes we are just in a hurry to try something and see if it will work.
