### ISSUE TITLE
Error when deploying from a Windows OS

### ISSUE THREAD

**Issue by 0ly** [FoxxMD/laravel-elasticbeanstalk-queue-worker#9]
I get the following error only when attempting to deploy with a windows machine. 

> INFO: Deploying new version to instance(s).
> **ERROR: [Instance: i-0a52f2c7b21b781e0] Command failed on instance. Return code: 127 Output: /usr/bin/env: bash**
> **: No such file or directory.**
> **container_command 005-workerDeploy in .ebextensions/99deployWorker.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.**
> INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
> ERROR: Unsuccessful command execution on instance id(s) 'i-0a51f2c7b81b781e7'. Aborting the operation.
> ERROR: Failed to deploy application.

I've used this package for over a year within my application using macOS to deploy and never had this error come up.

I assumed that the shell scripts included in this package (IE. workerDeploy.sh) were being ran within the AWS server, not the local machine deploying the application. Is that not the case?

**Comment by FoxxMD** [comment]
Everything in the `ebextensions` folder is only run by EB when deploying to the ec2 instance. Additionally the provider only publishes the config file and `ebextensions` folder to your project root and only if you explicitly publish it with `artisan` -- So if it is trying to execute on your local machine it must be something you are doing in your application.

When you saying "deploying from" do you mean you are zipping up the application on a Windows machine and then uploading that to the EB environment through cli/web interface and then using that to deploy to an instance? The only problems I can think of would be that Windows is messing with [line-endings](http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html) or perhaps windows doesn't like folders that are prefixed with a period IE `.ebextensions/workerDeploy.sh`

**Comment by FoxxMD** [comment]
@0ly was your issue resolved?
